### ISSUE TITLE
How to setup this with MetallB on a bare metal Cluster?

### ISSUE THREAD

**Issue by secretlifeof** [funkypenguin/docker-mailserver#8]
I am trying to setup in a bare metal Cluster on Hetzner Cloud. To be able to have LoadBalancer support I have installed MetallB and set it up to choose an IP-address from the internal network. So the IP is not directly accessible externally.

Related to #5 

Values.yml:
```
pod:
  dockermailserver:
    override_hostname: "mail.mydomain.com"
rainloop:
  ingress:
    hosts: 
      - "mail.mydomain.com"
domains:
  - "mydomain.com"
ssl:
  dnsname: "mail.mydomain.com"
  issuer:
    name: "letsencrypt-prod"
persistence:
  size: "30Gi"
haproxy-ingress:
  deploy_chart: true
  tcp:
    - 25: "default/docker-mailserver:25::30025"
    - 110: "default/docker-mailserver:110::30110"
    - 143: "default/docker-mailserver:143::30143"
    - 993: "default/docker-mailserver:993::30993"
    - 995: "default/docker-mailserver:993::30995"
haproxy:
  enabled: true
```

==> v1/Service
```
NAME                                               TYPE          CLUSTER-IP     EXTERNAL-IP  PORT(S)                                                                                                           
docker-mailserver                                  NodePort      10.56.201.205  <none>       25:30025/TCP,110:30110/TCP,143:30143/TCP,465:30465/TCP,587:30587/TCP,993:30993/TCP,995:30995/TCP,10993:32183/TCP  
docker-mailserver-haproxy-ingress-controller       LoadBalancer  10.56.70.225   10.250.0.12    110:32301/TCP,143:30360/TCP,25:31555/TCP,465:32659/TCP,587:31405/TCP,993:31780/TCP,995:31953/TCP                  
docker-mailserver-haproxy-ingress-default-backend  ClusterIP     10.56.143.104  <none>       8080/TCP                                                                                                          
docker-mailserver-rainloop                         ClusterIP     10.43.163.160  <none>       80/TCP                                                                                                            
```

## Errors:
404 when trying to browse to mail.mydomain.com

## Questions
- Do I need to assign a static IP that is directly externally accessible?

Any help would be appreciated :)
